[server.pv.addon.groups]
divider = "&8&m-----------------------------------------------------"

[server.pv.addon.groups.format]
group_name = "&6[%s]"
players_and_owner = "&7Игроки: &r%1$s&7, владелец: &r%2$s"
invite = "%1$s пригласил(а) вас в группу %2$s"
only_players = "&7Игроки: &r%s"
page = "&7Страница &r%s/%s"

[server.pv.addon.groups.tooltip]
group_uuid = "Uuid: %s"
password_protected = "Группа защищена паролем"

[server.pv.addon.groups.error]
not_in_group = "&cВы должны быть в группе для выполнения этой команды"
name_length = "&cИмя группы должно быть от %1$s до %2$s символов"
player_not_found = "&cНет игрока с таким именем"
unknown_subcommand = "&cНеизвестная команда. Доступные команды: %s"
unknown = "&cНеизвестная ошибка"
group_not_found = "&cГруппа не найдена"
uuid_parse = "&cОшибка распознавания Uuid. '%s' не является Uuid"
no_permission = "&cНет прав: '%s'"

[server.pv.addon.groups.icons]
password_protected = "&6⛨"

[server.pv.addon.groups.command.unset.error]
permissions_not_set = "&cФильтр прав уже пуст"
unknown_flag = "&cНельзя снять флаг \"%1$s\". Доступные флаги: %2$s"
password_not_set = "&cГруппа уже не защищена паролем"
usage = "&cИспользование: /groups unset <флаг>"

[server.pv.addon.groups.command.ban.error]
already_banned = "&cИгрок уже заблокирован в этой группе"
usage = "&cИспользование: /groups ban <player>"

[server.pv.addon.groups.command.leave]
success = "&aВы покинули группу"

[server.pv.addon.groups.command.create]
success = "&aГруппа создана:"

[server.pv.addon.groups.command.join]
success = "&%s присоединился к группе"

[server.pv.addon.groups.command.join.error]
already_joined = "&cВы уже присоединились к этой группе"
usage = "&cИспользование: /groups join <uuid группы> [пароль]"
banned = "&cВы были заблокированы в этой группе"

[server.pv.addon.groups.command.set.error]
unknown_flag = "&cНеизвестный флаг: \"%1$s\". Доступные флаги: %2$s"
usage = "&cИспользование: /groups set <флаг> <значение>"
identical_value = "&cЗначение идентично текущему значению"

[server.pv.addon.groups.command.unban.error]
not_banned = "&cИгрок не заблокирован в этой группе"
usage = "&cИспользование: /groups unban <player>"

[server.pv.addon.groups.command.transfer.error]
already_owner = "&cВы уже владелец группы"
usage = "&cИспользование: /groups transfer <игрок>"

[server.pv.addon.groups.command.kick.error]
not_in_group = "&cИгрок не находится в группе"
usage = "&cИспользование: /groups kick <player>"

[server.pv.addon.groups.command.invite]
success = "Приглашение отправлено %s"

[server.pv.addon.groups.command.invite.error]
already_joined = "&cИгрок уже присоединился к группе"
usage = "&cИспользование: /groups invite <игрок>"
banned = "&cИгрок заблокирован в этой группе"
invite_self = "&7Вы не можете пригласить самого себя"

[server.pv.addon.groups.command.browse.error]
page_not_found = "Страница не найдена"
no_groups = "&cНет групп. Создайте группу с помощью \"/groups create\""

[server.pv.addon.groups.button]
next = "&e>"
leave = "&c←Выйти"
prev = "&e<"
invite = "&e✉ Пригласить"
join = "&e→ Присоединиться"

[server.pv.addon.groups.arg]
groups_uuid = "<uuid группы>"
password = "<пароль>"
permissions = "<список прав, разделенных запятыми>"
name = "<название>"
page = "[страница]"

[server.pv.addon.groups.notifications]
player_unbanned = "%s был разблокирован в группе"
player_left = "%s покинул группу"
banned = "&cВы были заблокированы в группе"
new_owner = "Новый владелец группы: %s"
player_banned = "%s был заблокирован в группе"
persistent_false = "Теперь группа будет удалена после перезагрузки сервера"
player_kicked = "%s исключён из группы"
password_changed = "Пароль группы изменён"
kicked = "&cВы были исключены из группы"
persistent_true = "Теперь группа не будет удалена после перезагрузки сервера"
permissions_unset = "Защита правами была удалена"
group_deleted = "Группа удалена"
player_join = "%s присоединился к группе"
password_unset = "Защита паролем удалена"
permissions_changed = "Права группы изменены"
name_change = "Название группы было изменено с '%1$s' на '%2$s'"
[client.pv.activation]
groups = "Группы"
