name = "The Varp 1.0.0"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "900643c53260ac2554eb8ea8656cec670ac6fa734d10fe91f7c3827042e68beb"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
