name = "The Varp 1.0.0"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ff104cb76e84409cb30ce361daacdc5e3ffd749639c5bed376e6cbbd9f9a643"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
